# Generated by Django 5.2.4 on 2025-08-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book_image_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
