# Generated by Django 5.2.4 on 2025-08-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_book_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_id',
        ),
        migrations.AddField(
            model_name='book',
            name='source_type',
            field=models.IntegerField(choices=[(1, 'FBV'), (2, 'CBV')], default=1),
            preserve_default=False,
        ),
    ]
